# Generated by Django 3.2.18 on 2023-04-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='complexity_estimate',
            field=models.CharField(blank=True, choices=[('Intern', 'Intern'), ('Junior', 'Junior'), ('Midlevel', 'Mid-Level'), ('Senior', 'Senior'), ('CTO', 'CTO')], help_text='Difficult or Easy or not sure', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bounty',
            name='issue_id',
            field=models.CharField(blank=True, choices=[('Intern', 'Intern'), ('Junior', 'Junior'), ('Midlevel', 'Mid-Level'), ('Senior', 'Senior'), ('CTO', 'CTO')], help_text='GitHub ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
