# Generated by Django 3.2.18 on 2023-05-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0002_auto_20230428_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='framework',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='hosting_environment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='bug_screenshots'),
        ),
        migrations.AddField(
            model_name='issue',
            name='tags',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
