# Generated by Django 3.2.18 on 2023-05-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0003_auto_20230502_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='hosting',
            field=models.CharField(blank=True, help_text='Hosting provider if known', max_length=255),
        ),
        migrations.AddField(
            model_name='bounty',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma Seperated Tags', max_length=255),
        ),
    ]
