# Generated by Django 3.2.18 on 2023-05-12 22:55

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bounty', '0005_auto_20230512_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedBounty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('bounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bounty.bounty')),
                ('bounty_hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_bounties_hunted', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_bounties_owned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bountysetter',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bountysetter',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_signature', models.ImageField(blank=True, null=True, upload_to='contracts')),
                ('bounty_hunter_signature', models.ImageField(blank=True, null=True, upload_to='contracts')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('start_date'), '+', django.db.models.expressions.Value(datetime.timedelta(days=30)))), django.core.validators.MaxValueValidator(limit_value=django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('start_date'), '+', django.db.models.expressions.Value(datetime.timedelta(days=365))))])),
                ('accepted_bounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bounty.acceptedbounty')),
                ('bounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bounty.bounty')),
            ],
        ),
    ]
