# Generated by Django 3.2.18 on 2023-05-15 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0006_auto_20230512_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bountyhunter',
            old_name='address_line1',
            new_name='street_address',
        ),
        migrations.RenameField(
            model_name='bountysetter',
            old_name='address_line1',
            new_name='street_address',
        ),
    ]
