# Generated by Django 3.2.18 on 2023-05-15 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0007_auto_20230515_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bountyhunter',
            old_name='zip_code',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='bountysetter',
            old_name='zip_code',
            new_name='postal_code',
        ),
    ]
