# Generated by Django 3.2.18 on 2023-05-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0008_auto_20230515_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bountyhunter',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='bountyhunter',
            name='candidate_certification',
        ),
        migrations.RemoveField(
            model_name='bountyhunter',
            name='candidate_level',
        ),
        migrations.RemoveField(
            model_name='bountyhunter',
            name='candidate_resume',
        ),
        migrations.RemoveField(
            model_name='bountyhunter',
            name='candidate_skills',
        ),
        migrations.RemoveField(
            model_name='bountyhunter',
            name='city',
        ),
        migrations.RemoveField(
            model_name='bountyhunter',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='bountyhunter',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='bountyhunter',
            name='state',
        ),
        migrations.RemoveField(
            model_name='bountyhunter',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='bountysetter',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='bountysetter',
            name='city',
        ),
        migrations.RemoveField(
            model_name='bountysetter',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='bountysetter',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='bountysetter',
            name='state',
        ),
        migrations.RemoveField(
            model_name='bountysetter',
            name='street_address',
        ),
        migrations.AlterField(
            model_name='bounty',
            name='complexity_estimate',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Extreme', 'Extreme')], help_text='Difficult or Easy or not sure', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='issue_id',
            field=models.CharField(blank=True, help_text='GitHub ID', max_length=255, null=True),
        ),
    ]
