# Generated by Django 3.2.18 on 2023-05-26 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0009_auto_20230517_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bountyhunter',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bountyhunter',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='bountysetter',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bountysetter',
            name='full_name',
        ),
    ]
