# Generated by Django 3.2.19 on 2023-06-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0011_alter_bountysetter_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='complexity_estimate',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
