# Generated by Django 3.2.19 on 2023-06-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0012_auto_20230601_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='catagory',
            field=models.CharField(blank=True, choices=[('Bug', 'Bug'), ('Feature', 'Feature')], help_text="If it is new or it works but you want to change it somehow it's a feature, otherwise it's a bug", max_length=255),
        ),
    ]
