# Generated by Django 3.2.19 on 2023-06-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0013_bounty_catagory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('notes', models.TextField()),
                ('error_message', models.TextField()),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('steps_to_reproduce', models.TextField()),
                ('screenshots', models.ImageField(blank=True, upload_to='bug_screenshots')),
                ('is_user_submitted', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='bountyhunter',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
