# Generated by Django 3.2.19 on 2023-06-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0014_auto_20230628_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=255, unique=True)),
                ('team_size', models.PositiveIntegerField()),
                ('skills', models.TextField()),
                ('background', models.TextField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('project_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('industries_worked', models.CharField(choices=[('Technology', 'Technology'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare')], max_length=255)),
                ('github_repository', models.URLField()),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('linkedin_url', models.URLField()),
                ('how_they_found_us', models.TextField()),
            ],
        ),
    ]
