# Generated by Django 3.2.18 on 2023-08-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0015_developmentagency'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentagency',
            name='agency_type',
            field=models.CharField(blank=True, choices=[('Marketing', 'Marketing'), ('Software Development', 'Software Development'), ('Finance', 'Finance'), ('Investment Fund', 'Investment Fund'), ('Legal', 'Legal'), ('Accounting/Taxes', 'Accounting/Taxes'), ('Accelerator/Incubator', 'Accelerator/Incubator')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='developmentagency',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='agency-logo'),
        ),
        migrations.AlterField(
            model_name='developmentagency',
            name='background',
            field=models.TextField(help_text='How long have you been in business, where are you based details to help startups know who you are.'),
        ),
        migrations.AlterField(
            model_name='developmentagency',
            name='github_repository',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developmentagency',
            name='industries_worked',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('Government', 'Government'), ('Non/Profit-NGO', 'Non/Profit-NGO'), ('Manufacturing', 'Manufacturing'), ('Agriculture', 'Agriculture'), ('Climate Tech', 'Climate Tech')], help_text='Primary Industries you serve or have worked with', max_length=255),
        ),
        migrations.AlterField(
            model_name='developmentagency',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developmentagency',
            name='skills',
            field=models.TextField(blank=True, help_text='If your a service, list the skills your team uses to complete the service', null=True),
        ),
        migrations.AlterField(
            model_name='developmentagency',
            name='team_size',
            field=models.PositiveIntegerField(help_text='How many employees in your organization'),
        ),
    ]
