# Generated by Django 3.2.18 on 2023-08-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0016_auto_20230816_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentagency',
            name='client_reviews',
            field=models.TextField(blank=True, help_text="Profile Links to Clutch, Capterra, G2 Crowd, and GoodFirms: Links to the company's profiles on these review platforms.", max_length=255, null=True),
        ),
    ]
