# Generated by Django 3.2.18 on 2023-09-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0018_insightsuser_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insightsuser',
            name='organization_id',
        ),
        migrations.RemoveField(
            model_name='insightsuser',
            name='user_uuid',
        ),
        migrations.AddField(
            model_name='insightsuser',
            name='insightsorganization_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='insightsuser',
            name='insightsuser_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
