# Generated by Django 3.2.18 on 2023-11-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0019_auto_20230929_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='app_name',
            field=models.CharField(default='Insights', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bug',
            name='expected_behaviour',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bug',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bug',
            name='title',
            field=models.CharField(default='bug', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bug',
            name='version',
            field=models.CharField(default='v0.0.1', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bug',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bug',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
