# Generated by Django 3.2.18 on 2023-11-15 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0020_auto_20231115_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='bug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bounty.bug'),
        ),
    ]
