# Generated by Django 3.2.18 on 2023-11-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0021_issue_bug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='expected_behaviour',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bug',
            name='steps_to_reproduce',
            field=models.TextField(blank=True),
        ),
    ]
