# Generated by Django 3.2.18 on 2023-11-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0022_auto_20231115_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='app_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bug',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bug',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='bug',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bug',
            name='version',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
