# Generated by Django 3.2.18 on 2023-11-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0023_auto_20231117_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
