# Generated by Django 3.2.18 on 2023-11-22 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0025_auto_20231120_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='bug',
        ),
    ]
