# Generated by Django 3.2.18 on 2023-11-28 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0026_remove_issue_bug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='issue',
        ),
        migrations.AddField(
            model_name='bug',
            name='bounty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bug_bounty', to='bounty.bounty'),
        ),
    ]
