# Generated by Django 3.2.18 on 2023-12-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0027_auto_20231128_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='is_tracked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_tracked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='catagory',
            field=models.CharField(blank=True, choices=[('Bug', 'Bug'), ('Feature', 'Feature'), ('Puchlist', 'Punchlist'), ('Release', 'Release')], help_text="If it is new or it works but you want to change it somehow it's a feature, otherwise it's a bug.  A Punchlist is a list of bug in a release, and a release is collection of bugs and features", max_length=255),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='repo',
            field=models.CharField(help_text='GitHub Repository i.e. myorg/myrepo', max_length=100),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='repo_access_token',
            field=models.CharField(help_text='Learn how to get your GitHub Token here https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens', max_length=100),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='repo_owner',
            field=models.CharField(help_text='Github Organization Name', max_length=100),
        ),
    ]
