# Generated by Django 3.2.25 on 2024-07-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0028_auto_20231207_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='tracked_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='tracked_url',
            field=models.URLField(blank=True),
        ),
    ]
