# Generated by Django 3.2.16 on 2025-10-20 19:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgeApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('price_cents', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('repo_url', models.URLField(max_length=500)),
                ('repo_owner', models.CharField(max_length=100)),
                ('repo_name', models.CharField(max_length=100)),
                ('license_type', models.CharField(choices=[('BSL-1.1→Apache-2.0', 'BSL-1.1→Apache-2.0'), ('Apache-2.0', 'Apache-2.0'), ('MIT', 'MIT'), ('Other', 'Other')], max_length=50)),
                ('change_date_utc', models.DateTimeField(blank=True, null=True)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('targets', models.JSONField(blank=True, default=list)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('screenshots', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Forge App',
                'verbose_name_plural': 'Forge Apps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_labs_customer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forge_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='RepoValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('missing_items', models.JSONField(blank=True, default=list)),
                ('detected_targets', models.JSONField(blank=True, default=list)),
                ('validated_commit_sha', models.CharField(blank=True, max_length=40, null=True)),
                ('run_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('forge_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='forge.forgeapp')),
            ],
            options={
                'verbose_name': 'Repository Validation',
                'verbose_name_plural': 'Repository Validations',
                'ordering': ['-run_at'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('amount_cents', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_applied', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('requires_payment', 'Requires Payment'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='requires_payment', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forge_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='forge.forgeapp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forge_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forge_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='forge.forgeapp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forge_entitlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entitlement',
                'verbose_name_plural': 'Entitlements',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'forge_app')},
            },
        ),
    ]
