# Generated by Django 3.2.25 on 2025-10-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
