# Generated by Django 3.2.25 on 2025-10-21 23:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0002_auto_20251020_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgeapp',
            name='price_cents',
            field=models.IntegerField(default=0, help_text='Price in cents (e.g., 2999 for $29.99, 0 for free)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
