# Generated by Django 3.2.25 on 2025-12-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0003_alter_forgeapp_price_cents'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgeapp',
            name='demo_video_url',
            field=models.URLField(blank=True, help_text='YouTube, Vimeo, or direct video URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='forgeapp',
            name='last_release_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forgeapp',
            name='latest_release_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='forgeapp',
            name='latest_release_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='forgeapp',
            name='latest_release_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='forgeapp',
            name='latest_release_zip_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='forgeapp',
            name='video_type',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('direct', 'Direct URL')], default='youtube', help_text='Video platform type', max_length=20),
        ),
        migrations.AddField(
            model_name='purchase',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='last_downloaded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forgeapp',
            name='screenshots',
            field=models.JSONField(blank=True, default=list, help_text='List of screenshot URLs'),
        ),
    ]
