# Generated by Django 3.2.17 on 2023-02-03 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hunter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('position_title', models.CharField(blank=True, max_length=255)),
                ('position_pay', models.CharField(blank=True, max_length=255)),
                ('skills', models.CharField(blank=True, max_length=255)),
                ('level', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('plan', models.CharField(blank=True, max_length=255)),
                ('expriation_date', models.DateTimeField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hunters.hunter')),
            ],
        ),
        migrations.CreateModel(
            name='HunterEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(blank=True, max_length=255)),
                ('candidate_profile', models.CharField(blank=True, max_length=255)),
                ('candidate_certification', models.CharField(blank=True, max_length=255)),
                ('candidate_resume', models.CharField(blank=True, max_length=255)),
                ('candidate_skills', models.CharField(blank=True, max_length=255)),
                ('candidate_level', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hunters.hunter')),
            ],
        ),
    ]
