# Generated by Django 3.2.17 on 2023-02-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunter',
            name='linkedin_url',
            field=models.CharField(blank=True, help_text='Your LinkedIn Profile URL', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='description',
            field=models.TextField(blank=True, help_text='Describe in detail the type of person you are looking for'),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='level',
            field=models.CharField(blank=True, help_text='Skill level (Junior, Midlevel or Senior', max_length=255),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='name',
            field=models.CharField(blank=True, help_text='Name your hunt, i.e. The Search for Ops Commander', max_length=255),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='position_pay',
            field=models.CharField(blank=True, help_text='Pay Range', max_length=255),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='position_title',
            field=models.CharField(blank=True, help_text='Title, (CTO, Front End, Back End etc.)', max_length=255),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='skills',
            field=models.CharField(blank=True, help_text='Top Skills', max_length=255),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='status',
            field=models.CharField(blank=True, help_text='Acitivate the Hunt', max_length=255),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='url',
            field=models.CharField(blank=True, help_text='Your GitHub Profile URL', max_length=255, null=True),
        ),
    ]
