# Generated by Django 3.2.17 on 2023-02-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunters', '0002_auto_20230205_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunter',
            name='level',
            field=models.CharField(blank=True, choices=[('Intern', 'Intern'), ('Junior', 'Junior'), ('Midlevel', 'Mid-Level'), ('Senior', 'Senior'), ('CTO', 'CTO')], help_text='Skill level - Select One', max_length=255),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Planned', 'Planned'), ('Started', 'Started'), ('Found', 'Found'), ('CANCELED', 'CANCELED')], default='DRAFT', help_text='Acitivate the Hunt', max_length=255),
        ),
    ]
