# Generated by Django 3.2.17 on 2023-02-22 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunters', '0003_auto_20230214_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='hunter',
            name='brief',
            field=models.FileField(blank=True, help_text='Document Upload', upload_to=''),
        ),
        migrations.AddField(
            model_name='hunter',
            name='certification',
            field=models.TextField(blank=True, help_text='Certifications required if any'),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='position_title',
            field=models.ForeignKey(blank=True, help_text='Title, (CTO, Front End, Back End etc.)', on_delete=django.db.models.deletion.CASCADE, to='hunters.position'),
        ),
    ]
