# Generated by Django 3.2.17 on 2023-03-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunters', '0004_auto_20230222_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunter',
            name='language',
            field=models.CharField(blank=True, help_text='Langugae Requirements (English, Spanish Etc.)', max_length=255),
        ),
        migrations.AddField(
            model_name='hunter',
            name='location',
            field=models.CharField(blank=True, help_text='Geographic Location of Position', max_length=255),
        ),
        migrations.AddField(
            model_name='hunter',
            name='remote',
            field=models.CharField(blank=True, help_text='Remote, In-Office or Hybrid', max_length=255),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='brief',
            field=models.FileField(blank=True, help_text='Document Upload', null=True, upload_to=''),
        ),
    ]
