# Generated by Django 3.2.25 on 2024-08-22 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_member_type', models.CharField(choices=[('buildly-hire-frontend', 'Buildly Hire Frontend'), ('buildly-hire-backend', 'Buildly Hire Backend'), ('buildly-hire-ai', 'Buildly Hire AI'), ('buildly-hire-marketing', 'Buildly Hire Marketing'), ('buildly-hire-marketing-intern', 'Buildly Hire Marketing Intern'), ('community-frontend', 'Community Member Frontend'), ('community-backend', 'Community Member Backend'), ('community-ai', 'Community Member AI'), ('community-ui-designer', 'Community Member UI Designer'), ('community-ux', 'Community Member UX'), ('community-advisor', 'Community Member Advisor'), ('community-software-agency', 'Community Member Software Agency'), ('community-marketing-agency', 'Community Member Marketing Agency'), ('community-design-agency', 'Community Member Design Agency')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True)),
                ('document', models.FileField(blank=True, upload_to='resources/')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_member_type', models.CharField(choices=[('buildly-hire-frontend', 'Buildly Hire Frontend'), ('buildly-hire-backend', 'Buildly Hire Backend'), ('buildly-hire-ai', 'Buildly Hire AI'), ('buildly-hire-marketing', 'Buildly Hire Marketing'), ('buildly-hire-marketing-intern', 'Buildly Hire Marketing Intern'), ('community-frontend', 'Community Member Frontend'), ('community-backend', 'Community Member Backend'), ('community-ai', 'Community Member AI'), ('community-ui-designer', 'Community Member UI Designer'), ('community-ux', 'Community Member UX'), ('community-advisor', 'Community Member Advisor'), ('community-software-agency', 'Community Member Software Agency'), ('community-marketing-agency', 'Community Member Marketing Agency'), ('community-design-agency', 'Community Member Design Agency')], max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('github_account', models.URLField(blank=True)),
                ('google_account_link', models.URLField(blank=True)),
                ('google_calendar_embed_code', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
