# Generated by Django 3.2.25 on 2024-08-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='team_member_type',
            field=models.CharField(choices=[('all', 'Everyone'), ('buildly-hire-frontend', 'Buildly Hire Frontend'), ('buildly-hire-backend', 'Buildly Hire Backend'), ('buildly-hire-ai', 'Buildly Hire AI'), ('buildly-hire-marketing', 'Buildly Hire Marketing'), ('buildly-hire-marketing-intern', 'Buildly Hire Marketing Intern'), ('community-frontend', 'Community Member Frontend'), ('community-backend', 'Community Member Backend'), ('community-ai', 'Community Member AI'), ('community-ui-designer', 'Community Member UI Designer'), ('community-ux', 'Community Member UX'), ('community-advisor', 'Community Member Advisor'), ('community-software-agency', 'Community Member Software Agency'), ('community-marketing-agency', 'Community Member Marketing Agency'), ('community-design-agency', 'Community Member Design Agency')], max_length=50),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='team_member_type',
            field=models.CharField(choices=[('all', 'Everyone'), ('buildly-hire-frontend', 'Buildly Hire Frontend'), ('buildly-hire-backend', 'Buildly Hire Backend'), ('buildly-hire-ai', 'Buildly Hire AI'), ('buildly-hire-marketing', 'Buildly Hire Marketing'), ('buildly-hire-marketing-intern', 'Buildly Hire Marketing Intern'), ('community-frontend', 'Community Member Frontend'), ('community-backend', 'Community Member Backend'), ('community-ai', 'Community Member AI'), ('community-ui-designer', 'Community Member UI Designer'), ('community-ux', 'Community Member UX'), ('community-advisor', 'Community Member Advisor'), ('community-software-agency', 'Community Member Software Agency'), ('community-marketing-agency', 'Community Member Marketing Agency'), ('community-design-agency', 'Community Member Design Agency')], max_length=50),
        ),
    ]
