# Generated by Django 3.2.24 on 2025-02-03 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_auto_20240830_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMemberResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_complete', models.PositiveIntegerField(default=0)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.resource')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.teammember')),
            ],
        ),
        migrations.CreateModel(
            name='CertificationExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_member_type', models.CharField(choices=[('all', 'Everyone'), ('buildly-hire-frontend', 'Buildly Hire Frontend'), ('buildly-hire-backend', 'Buildly Hire Backend'), ('buildly-hire-ai', 'Buildly Hire AI'), ('buildly-hire-marketing', 'Buildly Hire Marketing'), ('buildly-hire-marketing-intern', 'Buildly Hire Marketing Intern'), ('community-frontend', 'Community Member Frontend'), ('community-backend', 'Community Member Backend'), ('community-ai', 'Community Member AI'), ('community-ui-designer', 'Community Member UI Designer'), ('community-ux', 'Community Member UX'), ('community-advisor', 'Community Member Advisor'), ('community-software-agency', 'Community Member Software Agency'), ('community-marketing-agency', 'Community Member Marketing Agency'), ('community-design-agency', 'Community Member Design Agency')], max_length=50)),
                ('exam_link', models.URLField()),
                ('score', models.PositiveIntegerField(default=0)),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.teammember')),
            ],
        ),
    ]
