# Generated by Django 3.2.24 on 2025-02-03 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onboarding', '0003_certificationexam_teammemberresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('available_date', models.DateField()),
                ('url', models.URLField(unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='certificationexam',
            name='team_member_type',
            field=models.CharField(choices=[('all', 'Everyone'), ('buildly-hire-frontend', 'Buildly Hire Frontend'), ('buildly-hire-backend', 'Buildly Hire Backend'), ('buildly-hire-ai', 'Buildly Hire AI'), ('buildly-hire-marketing', 'Buildly Hire Marketing'), ('buildly-hire-marketing-intern', 'Buildly Hire Marketing Intern'), ('community-member-generic', 'Generic Community Member'), ('community-frontend', 'Community Member Frontend'), ('community-backend', 'Community Member Backend'), ('community-ai', 'Community Member AI'), ('community-ui-designer', 'Community Member UI Designer'), ('community-ux', 'Community Member UX'), ('community-advisor', 'Community Member Advisor'), ('community-software-agency', 'Community Member Software Agency'), ('community-marketing-agency', 'Community Member Marketing Agency'), ('community-design-agency', 'Community Member Design Agency')], max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='team_member_type',
            field=models.CharField(choices=[('all', 'Everyone'), ('buildly-hire-frontend', 'Buildly Hire Frontend'), ('buildly-hire-backend', 'Buildly Hire Backend'), ('buildly-hire-ai', 'Buildly Hire AI'), ('buildly-hire-marketing', 'Buildly Hire Marketing'), ('buildly-hire-marketing-intern', 'Buildly Hire Marketing Intern'), ('community-member-generic', 'Generic Community Member'), ('community-frontend', 'Community Member Frontend'), ('community-backend', 'Community Member Backend'), ('community-ai', 'Community Member AI'), ('community-ui-designer', 'Community Member UI Designer'), ('community-ux', 'Community Member UX'), ('community-advisor', 'Community Member Advisor'), ('community-software-agency', 'Community Member Software Agency'), ('community-marketing-agency', 'Community Member Marketing Agency'), ('community-design-agency', 'Community Member Design Agency')], max_length=50),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='team_member_type',
            field=models.CharField(choices=[('all', 'Everyone'), ('buildly-hire-frontend', 'Buildly Hire Frontend'), ('buildly-hire-backend', 'Buildly Hire Backend'), ('buildly-hire-ai', 'Buildly Hire AI'), ('buildly-hire-marketing', 'Buildly Hire Marketing'), ('buildly-hire-marketing-intern', 'Buildly Hire Marketing Intern'), ('community-member-generic', 'Generic Community Member'), ('community-frontend', 'Community Member Frontend'), ('community-backend', 'Community Member Backend'), ('community-ai', 'Community Member AI'), ('community-ui-designer', 'Community Member UI Designer'), ('community-ux', 'Community Member UX'), ('community-advisor', 'Community Member Advisor'), ('community-software-agency', 'Community Member Software Agency'), ('community-marketing-agency', 'Community Member Marketing Agency'), ('community-design-agency', 'Community Member Design Agency')], max_length=50),
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_member_type', models.CharField(choices=[('all', 'Everyone'), ('buildly-hire-frontend', 'Buildly Hire Frontend'), ('buildly-hire-backend', 'Buildly Hire Backend'), ('buildly-hire-ai', 'Buildly Hire AI'), ('buildly-hire-marketing', 'Buildly Hire Marketing'), ('buildly-hire-marketing-intern', 'Buildly Hire Marketing Intern'), ('community-member-generic', 'Generic Community Member'), ('community-frontend', 'Community Member Frontend'), ('community-backend', 'Community Member Backend'), ('community-ai', 'Community Member AI'), ('community-ui-designer', 'Community Member UI Designer'), ('community-ux', 'Community Member UX'), ('community-advisor', 'Community Member Advisor'), ('community-software-agency', 'Community Member Software Agency'), ('community-marketing-agency', 'Community Member Marketing Agency'), ('community-design-agency', 'Community Member Design Agency')], max_length=50)),
                ('question', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('essay', 'Essay')], max_length=20)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='onboarding.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='onboarding.quizquestion')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.teammember')),
            ],
        ),
    ]
