# Generated by Django 3.2.24 on 2025-02-04 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_auto_20250203_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationexam',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onboarding.quiz'),
        ),
    ]
