# Generated by Django 3.2.25 on 2025-08-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0007_auto_20250310_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=255)),
                ('team_size', models.CharField(blank=True, max_length=100)),
                ('skills', models.TextField(blank=True)),
                ('background', models.TextField(blank=True)),
                ('hourly_rate', models.CharField(blank=True, max_length=100)),
                ('project_rate', models.CharField(blank=True, max_length=100)),
                ('industries_worked', models.CharField(blank=True, choices=[('Technology', 'Technology'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('Government', 'Government'), ('Non/Profit-NGO', 'Non/Profit-NGO'), ('Manufacturing', 'Manufacturing'), ('Agriculture', 'Agriculture'), ('Climate Tech', 'Climate Tech')], max_length=100)),
                ('agency_type', models.CharField(blank=True, choices=[('Marketing', 'Marketing'), ('Software Development', 'Software Development'), ('Finance', 'Finance'), ('Investment Fund', 'Investment Fund'), ('Legal', 'Legal'), ('Accounting/Taxes', 'Accounting/Taxes'), ('Accelerator/Incubator', 'Accelerator/Incubator')], max_length=100)),
                ('github_repository', models.URLField(blank=True)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('linkedin_url', models.URLField(blank=True)),
                ('how_they_found_us', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='agency-logo')),
            ],
        ),
    ]
