# Generated by Django 3.2.25 on 2025-12-11 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onboarding', '0008_developmentagency'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswer',
            name='ai_detection_analysis',
            field=models.TextField(blank=True, help_text='Detailed AI detection analysis'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='ai_detection_score',
            field=models.FloatField(blank=True, help_text='0-100 score indicating likelihood of AI usage', null=True),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='evaluated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='evaluated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='evaluator_notes',
            field=models.TextField(blank=True, help_text='Notes from human evaluator'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='evaluator_score',
            field=models.IntegerField(blank=True, help_text='Score given by human evaluator (e.g., 1-4 for A-D)', null=True),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='quizanswer',
            unique_together={('question', 'team_member')},
        ),
    ]
