# Generated by Django 3.2.25 on 2025-12-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0009_auto_20251211_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='assessment_completed_at',
            field=models.DateTimeField(blank=True, help_text='When assessment was completed', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='assessment_last_reminded',
            field=models.DateTimeField(blank=True, help_text='Last time reminded about assessment', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='assessment_reminder_count',
            field=models.IntegerField(default=0, help_text='Number of times reminded to complete assessment'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='has_completed_assessment',
            field=models.BooleanField(default=False, help_text='Has completed Developer Level Assessment'),
        ),
    ]
