# Generated by Django 3.2.25 on 2025-12-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0010_auto_20251211_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='resources',
            field=models.ManyToManyField(blank=True, help_text='Learning resources associated with this quiz', related_name='quizzes', to='onboarding.Resource'),
        ),
    ]
