# Generated by Django 3.2.25 on 2025-12-16 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0008_auto_agency_profile_types'),
        ('onboarding', '0013_customer_share_token_and_through_model'),
    ]

    operations = [
    ]
