# Generated by Django 3.2.25 on 2025-12-17 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0014_merge_20251216_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Associated agency if not registered on platform', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='onboarding.developmentagency'),
        ),
        migrations.CreateModel(
            name='TechnologySkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(choices=[('javascript', 'JavaScript'), ('python', 'Python'), ('typescript', 'TypeScript'), ('nodejs', 'Node.js'), ('kubernetes', 'Kubernetes'), ('git', 'Git'), ('bash', 'Bash/Shell'), ('react', 'React'), ('vue', 'Vue.js'), ('angular', 'Angular'), ('django', 'Django'), ('flask', 'Flask'), ('docker', 'Docker'), ('aws', 'AWS'), ('azure', 'Azure'), ('gcp', 'Google Cloud')], max_length=50)),
                ('skill_level', models.IntegerField(choices=[(1, '1 - Beginner'), (2, '2 - Elementary'), (3, '3 - Intermediate'), (4, '4 - Advanced'), (5, '5 - Expert')], default=1)),
                ('github_calculated_level', models.IntegerField(blank=True, help_text='Skill level calculated from GitHub data', null=True)),
                ('github_repos_count', models.IntegerField(default=0, help_text='Number of repos using this technology')),
                ('github_lines_count', models.IntegerField(default=0, help_text='Approximate lines of code in this technology')),
                ('last_github_sync', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about experience')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_skills', to='onboarding.teammember')),
            ],
            options={
                'ordering': ['-skill_level', 'technology'],
                'unique_together': {('team_member', 'technology')},
            },
        ),
    ]
