# Generated by Django 3.2.25 on 2025-12-17 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onboarding', '0016_auto_20251217_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentagency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='developmentagency',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Agency approved to access portal'),
        ),
        migrations.AddField(
            model_name='developmentagency',
            name='user',
            field=models.OneToOneField(blank=True, help_text='User account for agency login', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
