# Generated by Django 3.2.25 on 2025-12-17 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onboarding', '0017_auto_20251217_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='auto_renew',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='billing_enabled',
            field=models.BooleanField(default=False, help_text='Enable billing for this contract'),
        ),
        migrations.AddField(
            model_name='contract',
            name='billing_enabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='billing_enabled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_billing_enabled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='billing_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='billing_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('custom', 'Custom')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='contract',
            name='billing_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('onboarding', 'Onboarding'), ('engagement', 'Engagement'), ('maintenance', 'Maintenance')], default='engagement', max_length=20),
        ),
        migrations.AddField(
            model_name='contract',
            name='signature_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of signer', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='signature_timestamp',
            field=models.DateTimeField(blank=True, help_text='Server timestamp of signature', null=True),
        ),
        migrations.AddField(
            model_name='customerdeveloperassignment',
            name='notification_sent',
            field=models.BooleanField(default=False, help_text='Notification sent to developer'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='community_approval_date',
            field=models.DateTimeField(blank=True, help_text='When approved to Buildly community', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='community_approval_notification_sent',
            field=models.BooleanField(default=False, help_text='Notification sent to developer'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='community_approved_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who approved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signed_by',
            field=models.CharField(blank=True, help_text='Full name of person who signed', max_length=255),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('community_approved', 'Community Approval'), ('team_approved', 'Team Approval'), ('team_removal_requested', 'Removal Request'), ('team_removal_30day', '30-Day Removal Notice'), ('contract_ready', 'Contract Ready to Sign'), ('contract_signed', 'Contract Signed'), ('billing_enabled', 'Billing Enabled'), ('custom', 'Custom Message')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link_url', models.URLField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='onboarding.contract')),
                ('related_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='onboarding.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labs_username', models.CharField(max_length=255)),
                ('labs_email', models.EmailField(max_length=254)),
                ('labs_token', models.TextField(help_text='Encrypted API token for Labs')),
                ('labs_user_id', models.CharField(max_length=255, unique=True)),
                ('buildly_profile_linked', models.BooleanField(default=True, help_text='One unified Buildly profile')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('team_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='labs_account', to='onboarding.teammember')),
            ],
            options={
                'ordering': ['-linked_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('company_size', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company-logos/')),
                ('billing_address', models.TextField(blank=True)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('is_labs_customer', models.BooleanField(default=False)),
                ('labs_account_email', models.EmailField(blank=True, max_length=254)),
                ('labs_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='onboarding.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('billing', 'Billing Only'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('can_approve_developers', models.BooleanField(default=False)),
                ('can_sign_contracts', models.BooleanField(default=False)),
                ('can_manage_billing', models.BooleanField(default=False)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='onboarding.customer')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_admin_invitations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_admin_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accepted_at'],
                'unique_together': {('customer', 'user')},
            },
        ),
        migrations.AddField(
            model_name='customerdeveloperassignment',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Company admin who approved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer_approvals', to='onboarding.companyadmin'),
        ),
    ]
