# Generated by Django 3.2.25 on 2025-12-17 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0018_auto_20251217_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash for contract verification and tamper detection', max_length=64),
        ),
        migrations.CreateModel(
            name='ContractLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('team', 'Team Services'), ('hosting', 'Hosting Fees'), ('product_mgmt', 'Product Management'), ('training', 'Developer Training & Onboarding'), ('architecture', 'Software Architecture'), ('other', 'Other Services')], max_length=20)),
                ('description', models.CharField(help_text='Service description', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, help_text='Quantity or hours', max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('billing_frequency', models.CharField(choices=[('one_time', 'One-Time'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='monthly', max_length=20)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Discount %', max_digits=5)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or conditions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='onboarding.contract')),
            ],
            options={
                'ordering': ['service_type', 'created_at'],
            },
        ),
    ]
