# Generated by Django 3.2.25 on 2025-12-17 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onboarding', '0019_auto_20251217_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Frontend React Specialist, Python Backend Expert', max_length=255)),
                ('level_type', models.CharField(choices=[('junior', 'Junior'), ('intermediate', 'Intermediate'), ('senior', 'Senior'), ('expert', 'Expert'), ('specialty', 'Specialty')], default='intermediate', max_length=20)),
                ('description', models.TextField(help_text='What this certification demonstrates')),
                ('requirements', models.TextField(blank=True, help_text='Skills and experience required')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Cost to obtain certification', max_digits=10, null=True)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated list of skills')),
                ('badge_color', models.CharField(default='#3B82F6', help_text='Hex color for badge', max_length=7)),
                ('certificate_template', models.CharField(default='default', help_text='Template name for certificate design', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['level_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Generated PDF of signed contract', null=True, upload_to='contracts/pdf/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='png_file',
            field=models.FileField(blank=True, help_text='Generated PNG image of signed contract', null=True, upload_to='contracts/png/'),
        ),
        migrations.CreateModel(
            name='DeveloperCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Certification expiration date', null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Exam score or completion percentage', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about certification')),
                ('certificate_hash', models.CharField(blank=True, help_text='SHA256 hash for certificate verification', max_length=64)),
                ('certificate_number', models.CharField(help_text='Unique certificate ID', max_length=50, unique=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/pdf/')),
                ('png_file', models.FileField(blank=True, null=True, upload_to='certificates/png/')),
                ('is_revoked', models.BooleanField(default=False, help_text='Revoke if certification is no longer valid')),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.TextField(blank=True)),
                ('certification_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to', to='onboarding.certificationlevel')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications_earned', to='onboarding.teammember')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications_issued', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications_revoked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
                'unique_together': {('developer', 'certification_level')},
            },
        ),
    ]
