# Generated by Django 3.2.25 on 2025-12-18 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onboarding', '0020_auto_20251217_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerIntakeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=255)),
                ('products', models.TextField(help_text='Comma-separated list of selected products')),
                ('timeline', models.CharField(max_length=100)),
                ('preferences', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('contacted', 'Contacted'), ('converted', 'Converted to Customer'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for tracking')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_intake_requests', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='Linked Customer record if converted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_requests', to='onboarding.customer')),
            ],
            options={
                'verbose_name': 'Customer Intake Request',
                'verbose_name_plural': 'Customer Intake Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
