# Generated by Django 3.2.25 on 2025-12-18 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onboarding', '0022_developertrainingenrollment_teamtraining'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Team name (e.g., 'Frontend Team', 'Mobile Squad')", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer_teams_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_teams', to='onboarding.customer')),
                ('members', models.ManyToManyField(blank=True, related_name='developer_teams', to='onboarding.TeamMember')),
                ('team_lead', models.ForeignKey(blank=True, help_text='Optional team lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_led', to='onboarding.teammember')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('customer', 'name')},
            },
        ),
        migrations.AddField(
            model_name='teamtraining',
            name='developer_team',
            field=models.ForeignKey(blank=True, help_text='Optional: assign to specific team within customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to='onboarding.developerteam'),
        ),
    ]
