# Generated by Django 3.2.16 on 2025-12-29 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '000X_migrate_team_member_types'),
        ('onboarding', '0023_auto_20251218_2214'),
    ]

    operations = [
    ]
