# Generated by Django 3.2.16 on 2026-01-06
# Migration for developer availability and Forge project requests

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forge', '0001_initial'),
        ('onboarding', '0028_training_projects'),
    ]

    operations = [
        # Add availability fields to TeamMember
        migrations.AddField(
            model_name='teammember',
            name='available_for_public_projects',
            field=models.BooleanField(default=False, help_text='Available to work on public/open source Forge projects'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='available_for_customer_work',
            field=models.BooleanField(default=False, help_text='Available to work for Buildly customers'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='availability_start',
            field=models.CharField(
                blank=True,
                choices=[
                    ('immediate', 'Immediately Available'),
                    ('1_week', '1 Week from Now'),
                    ('2_weeks', '2 Weeks from Now'),
                    ('1_month', '1 Month from Now'),
                    ('custom', 'Custom Date'),
                ],
                default='immediate',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='teammember',
            name='availability_start_date',
            field=models.DateField(blank=True, help_text="Custom start date if 'Custom Date' selected", null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='hours_per_week',
            field=models.PositiveIntegerField(default=0, help_text='Hours per week available for work'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='availability_notes',
            field=models.TextField(blank=True, help_text='Additional notes about availability'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='availability_updated_at',
            field=models.DateTimeField(blank=True, help_text='When availability was last updated', null=True),
        ),
        
        # Create ForgeProjectRequest model
        migrations.CreateModel(
            name='ForgeProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(
                    choices=[
                        ('start_new', 'Start a New Project'),
                        ('fork_existing', 'Fork an Existing Project'),
                        ('contribute', 'Contribute to Existing Project'),
                    ],
                    default='start_new',
                    max_length=20,
                )),
                ('status', models.CharField(
                    choices=[
                        ('draft', 'Draft'),
                        ('submitted', 'Submitted'),
                        ('under_review', 'Under Review'),
                        ('approved', 'Approved'),
                        ('in_progress', 'In Progress'),
                        ('completed', 'Completed'),
                        ('rejected', 'Rejected'),
                    ],
                    default='draft',
                    max_length=20,
                )),
                ('project_name', models.CharField(help_text='Proposed project name', max_length=200)),
                ('project_description', models.TextField(help_text='Describe the project, its goals, and intended features')),
                ('target_category', models.CharField(blank=True, help_text='Target category (e.g., AI, Analytics, CRM)', max_length=100)),
                ('technologies', models.TextField(blank=True, help_text='Technologies you plan to use')),
                ('github_repo_url', models.URLField(blank=True, help_text='GitHub repo URL (if forking or contributing)')),
                ('needs_team', models.BooleanField(default=False, help_text='Looking for team members to help')),
                ('team_size', models.CharField(
                    blank=True,
                    choices=[
                        ('solo', 'Solo (Just me)'),
                        ('small', 'Small (2-3 people)'),
                        ('medium', 'Medium (4-6 people)'),
                        ('large', 'Large (7+ people)'),
                    ],
                    default='solo',
                    max_length=20,
                )),
                ('roles_needed', models.TextField(blank=True, help_text="Roles/skills you're looking for (e.g., Frontend, Backend, DevOps)")),
                ('team_description', models.TextField(blank=True, help_text='Describe the team and collaboration expectations')),
                ('estimated_duration', models.CharField(blank=True, help_text='Estimated project duration', max_length=100)),
                ('planned_start_date', models.DateField(blank=True, help_text='When you plan to start', null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Admin notes/feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('developer', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='forge_project_requests',
                    to='onboarding.teammember',
                )),
                ('existing_forge_app', models.ForeignKey(
                    blank=True,
                    help_text='Existing Forge app to fork/contribute to',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='fork_requests',
                    to='forge.forgeapp',
                )),
                ('reviewed_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='reviewed_forge_requests',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('team_members', models.ManyToManyField(
                    blank=True,
                    help_text='Developers who joined this project',
                    related_name='forge_project_teams',
                    to='onboarding.TeamMember',
                )),
            ],
            options={
                'verbose_name': 'Forge Project Request',
                'verbose_name_plural': 'Forge Project Requests',
                'ordering': ['-created_at'],
            },
        ),
        
        # Create ForgeTeamApplication model
        migrations.CreateModel(
            name='ForgeTeamApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Why do you want to join this project?')),
                ('skills_offered', models.TextField(help_text='What skills/experience can you contribute?')),
                ('hours_available', models.PositiveIntegerField(default=10, help_text='Hours per week you can contribute')),
                ('status', models.CharField(
                    choices=[
                        ('pending', 'Pending'),
                        ('accepted', 'Accepted'),
                        ('rejected', 'Rejected'),
                        ('withdrawn', 'Withdrawn'),
                    ],
                    default='pending',
                    max_length=20,
                )),
                ('response_message', models.TextField(blank=True, help_text='Response from project lead')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='forge_team_applications',
                    to='onboarding.teammember',
                )),
                ('project_request', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='applications',
                    to='onboarding.forgeprojectrequest',
                )),
            ],
            options={
                'verbose_name': 'Forge Team Application',
                'verbose_name_plural': 'Forge Team Applications',
                'ordering': ['-created_at'],
                'unique_together': {('project_request', 'applicant')},
            },
        ),
    ]
