# Generated by Django 3.2.16 on 2026-01-08
# Migration for CommunityNewsletter model

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onboarding', '0029_developer_availability_forge_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('custom_message', models.TextField(help_text='Custom message to include at the top of the newsletter')),
                ('total_customers', models.PositiveIntegerField(default=0)),
                ('total_developers', models.PositiveIntegerField(default=0)),
                ('new_customers_this_month', models.PositiveIntegerField(default=0)),
                ('new_developers_this_month', models.PositiveIntegerField(default=0)),
                ('active_opportunities', models.PositiveIntegerField(default=0)),
                ('open_source_projects', models.PositiveIntegerField(default=0)),
                ('recipient_count', models.PositiveIntegerField(default=0, help_text='Number of developers who received the email')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletters_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Newsletter',
                'verbose_name_plural': 'Community Newsletters',
                'ordering': ['-sent_at'],
            },
        ),
    ]
