# Generated by Django 3.2.16 on 2026-01-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0032_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='wellfound_profile',
            field=models.URLField(blank=True, help_text='Wellfound (AngelList) profile URL, e.g. https://wellfound.com/u/username'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key_prefix',
            field=models.CharField(help_text='First 12 chars of key for identification', max_length=20),
        ),
        migrations.AlterField(
            model_name='communitynewsletter',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('completed', 'Completed'), ('paused', 'Paused')], default='draft', max_length=20),
        ),
    ]
