# Generated by Django 3.2.16 on 2026-01-17 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onboarding', '0034_community_certification_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_message', models.TextField(blank=True, help_text='Personal message to include in the invitation email')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('opened', 'Opened'), ('started', 'Started'), ('expired', 'Expired')], default='sent', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_error', models.TextField(blank=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_invitations', to='onboarding.teammember')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_cert_invitations', to=settings.AUTH_USER_MODEL)),
                ('suggested_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onboarding.certificationtrack')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
