# Generated by Django 3.2.16 on 2026-01-17 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0035_add_certification_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerpublicprofile',
            name='github_access_token',
            field=models.CharField(blank=True, help_text='GitHub OAuth access token for API calls', max_length=255),
        ),
        migrations.AddField(
            model_name='developerpublicprofile',
            name='github_followers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='developerpublicprofile',
            name='github_stars',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='developerpublicprofile',
            name='github_token_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developerpublicprofile',
            name='openbuild_profile_url',
            field=models.URLField(blank=True, help_text='Your open.build profile URL'),
        ),
    ]
