# Generated by Django 3.2.16 on 2026-01-17 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onboarding', '0036_add_openbuild_and_github_oauth_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationlevel',
            name='track',
            field=models.CharField(choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('product_manager', 'Product Manager'), ('ai', 'AI/ML Developer'), ('ai_ethics', 'AI Ethical Developer'), ('leadership', 'Leadership'), ('general', 'General')], default='general', help_text='Certification track', max_length=50),
        ),
        migrations.AlterField(
            model_name='certificationtrack',
            name='key',
            field=models.CharField(choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('product_manager', 'Product Manager'), ('ai', 'AI/ML Developer'), ('ai_ethics', 'AI Ethical Developer'), ('leadership', 'Leadership')], max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='CompositeCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Unique identifier, e.g., 'cto_lead'", max_length=50, unique=True)),
                ('name', models.CharField(help_text="e.g., 'CTO/Lead Certification'", max_length=100)),
                ('description', models.TextField(help_text='What this composite certification represents')),
                ('min_level', models.PositiveIntegerField(default=3, help_text='Minimum level required in each track')),
                ('min_total_tracks', models.PositiveIntegerField(default=3, help_text='Minimum total number of tracks needed at required level')),
                ('icon', models.CharField(default='🏆', help_text='Emoji or icon class', max_length=50)),
                ('color', models.CharField(default='#F59E0B', help_text='Badge/certificate color', max_length=7)),
                ('badge_color', models.CharField(default='#F59E0B', max_length=7)),
                ('certificate_template', models.CharField(default='cto_lead', help_text='Template name', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('required_tracks', models.ManyToManyField(blank=True, help_text='Specific tracks that MUST be completed (e.g., Leadership)', related_name='composite_requirements', to='onboarding.CertificationTrack')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeveloperCompositeCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the award')),
                ('certificate_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('verification_hash', models.CharField(blank=True, max_length=64)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/composite/pdf/')),
                ('png_file', models.FileField(blank=True, null=True, upload_to='certificates/composite/png/')),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to', to='onboarding.compositecertification')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composite_certifications', to='onboarding.teammember')),
                ('qualifying_tracks', models.ManyToManyField(help_text='The Level 3 tracks that qualified this certification', related_name='composite_qualifications', to='onboarding.CertificationTrack')),
            ],
            options={
                'ordering': ['-awarded_at'],
                'unique_together': {('developer', 'certification')},
            },
        ),
    ]
