# Generated by Django 3.2.16 on 2026-01-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0037_add_ai_leadership_tracks_and_composite_certs'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerpublicprofile',
            name='github_top_repos',
            field=models.JSONField(blank=True, default=list, help_text='Cached top repositories data'),
        ),
    ]
