# Generated by Django 4.2.11 on 2024-08-06 19:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('punchlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentagency',
            name='certified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='punchlist',
            name='labs_organization_uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Organization UUID from Buildly Insights API', unique=True),
        ),
        migrations.AddField(
            model_name='punchlist',
            name='labs_product_id',
            field=models.CharField(blank=True, help_text='Product ID from Buildly Insights API', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='punchlist',
            name='labs_product_name',
            field=models.CharField(blank=True, help_text='Product Name from Buildly Insights API', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='punchlist',
            name='labs_release_id',
            field=models.JSONField(blank=True, help_text='Release IDs from Buildly Insights API for Product', max_length=255, null=True),
        ),
    ]
