# Generated by Django 4.2.11 on 2024-08-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punchlist', '0002_developmentagency_certified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='punchlist',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Make this public for anyone to work on'),
        ),
    ]
