# Generated by Django 3.2.25 on 2024-08-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punchlist', '0005_alter_product_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
