# Generated by Django 3.2.25 on 2024-10-07 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('punchlist', '0008_auto_20240904_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='punchlisthunter',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='punchlist.developmentagency'),
        ),
    ]
