# Generated by Django 3.2.25 on 2024-11-12 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('punchlist', '0009_punchlisthunter_agency'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('platfrom_url', models.URLField(blank=True, null=True)),
                ('rating', models.FloatField()),
                ('review_text', models.TextField(blank=True, null=True)),
                ('review_link', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punchlist.developmentagency')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyAggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.FloatField()),
                ('review_count', models.IntegerField()),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('agency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='punchlist.developmentagency')),
            ],
        ),
    ]
