# Generated by Django 3.2.25 on 2025-02-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punchlist', '0010_agencyaggregate_agencyreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punchlist',
            name='labs_organization_uuid',
            field=models.UUIDField(blank=True, help_text='Organization UUID from Buildly Insights API', null=True),
        ),
    ]
